### PR TITLE
Implemented support for FUSE 3 and building using CMake.

### PR DESCRIPTION
**Pull request by KOLANICH**
Added packaging using CPack.
Added some hardening.
.gitignored some files
Fixed some compiler warnings.
Implemented FUSE 3 compatibility

### CODE REVIEW

**Comment by KOLANICH** [comment]
@joeyhub

**Comment by KOLANICH** [comment]
@joeyhub

**Comment by KOLANICH** [comment]
@joeyhub

**Comment by KOLANICH** [comment]
@joeyhub

**Comment by joeyhub** [comment]
I will take a look at this sometime this week and see if necessary if I can add others to be able to check pull requests.

**Comment by KOLANICH** [comment]
Thanks for your attention.

**Pull request merged**
